# Generated by Django 4.2.14 on 2024-08-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='hospital',
            name='amenity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='emergency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='hospital',
            name='healthcare',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hospital',
            name='operator_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
