# Generated by Django 4.2.14 on 2024-09-11 17:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_remove_hospital_contact_number_hospital_amenity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='emergency',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='operator_type',
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
